# -*- coding: utf-8 -*-
"""volume_of_sphere

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqjSCwnuUHeA7NJ2vIMasWgrb5uyfSRP
"""

def calculate_volume_of_sphere(radius):
	pi = 3.14
	volume = 4/3*pi*(radius^3)
	return volume

radius_1 = 30
result = calculate_volume_of_sphere(radius_1)
print(result)
radius_1 = 40
result = calculate_volume_of_sphere(radius_1)
print(result)